# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 14:49
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surl', models.CharField(max_length=16, unique=True, verbose_name=b'Short URL')),
                ('title', models.CharField(blank=True, help_text=b'This may be used as a title, section or figure heading.', max_length=250, verbose_name=b'Title')),
                ('description', models.TextField(blank=True, help_text=b'May only be necessary where the content may not provide sufficient context.', verbose_name=b'Description')),
                ('creator_ip', models.GenericIPAddressField(blank=True, default=b'255.255.255.255', null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('licence', models.CharField(choices=[(b'(c)', b'All Rights Reserved'), (b'CC0', b'No Rights Reserved'), (b'CC BY', b'CC Attribution'), (b'CC BY-ND', b'CC Attribution + NoDerivatives'), (b'CC BY-SA', b'CC Attribution + ShareAlike'), (b'CC BY-NC', b'CC Attribution + Noncommercial'), (b'CC BY-NC-ND', b'CC Attribution + Noncommercial + NoDerivatives'), (b'CC BY-NC-SA', b'CC Attribution + Noncommercial + ShareAlike')], default=b'All Rights Reserved', help_text=b'What form of copyright do you offer?', max_length=50, verbose_name=b'Release Licence')),
                ('citation', models.CharField(blank=True, default=b'', help_text=b"Please reference the original creator, if it wasn't you.", max_length=150)),
                ('jsonresponse', jsonfield.fields.JSONField(blank=True, null=True)),
                ('reverted_from_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, help_text=b'An elaboration of the title.', max_length=500, verbose_name=b'Subtitle')),
                ('content', models.TextField(blank=True, help_text=b'Use html format to enter text.', verbose_name=b'Content')),
                ('custom_div', models.CharField(blank=True, help_text=b'Use html format to enter text.', max_length=500, verbose_name=b'Custom Div')),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiqi_text_creator', to=settings.AUTH_USER_MODEL)),
                ('reverted_from_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiqi_text_reverted_from', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('created_on',),
                'abstract': False,
                'db_table': 'text',
                'verbose_name_plural': 'Texts',
                'get_latest_by': 'created_on',
            },
            managers=[
                ('wiqi_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Wiqi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surl', models.CharField(max_length=16, unique=True, verbose_name=b'Short URL')),
                ('is_live_from', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text=b'Leave blank to publish immediately, otherwise select a future publication date.', null=True, verbose_name=b'Publish from')),
                ('is_live_to', models.DateTimeField(blank=True, help_text=b'Leave blank for permanent publication, otherwise select a date to end publication.', null=True, verbose_name=b'Publish until')),
                ('is_active', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('stack_object_id', models.PositiveIntegerField(null=True)),
                ('branched_object_id', models.PositiveIntegerField(null=True)),
                ('merged_object_id', models.PositiveIntegerField(null=True)),
                ('currency', models.CharField(choices=[(b'gbp', b'&pound;'), (b'usd', b'$'), (b'eur', b'&euro;')], default=b'gbp', max_length=7)),
                ('read_if', models.CharField(choices=[(b'open', b'Open'), (b'login', b'Login'), (b'own', b'Own')], default=b'own', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('branched_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiqi_wiqi_branched', to='contenttypes.ContentType')),
                ('branchlist', models.ManyToManyField(blank=True, related_name='_wiqi_branchlist_+', to='wiqi.Wiqi')),
                ('merged_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiqi_wiqi_merged', to='contenttypes.ContentType')),
                ('next_wiqi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiqi_wiqi_next', to='wiqi.Wiqi')),
                ('previous_wiqi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiqi_wiqi_previous', to='wiqi.Wiqi')),
                ('stack_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiqi_wiqi_base', to='contenttypes.ContentType')),
            ],
            options={
                'permissions': (('can_create', 'Can create new documents.'), ('can_view', 'Can view private object.'), ('can_view_stack', 'Can view history of private object.'), ('can_edit', 'Can edit private object and its history.'), ('can_publish', 'Can change publication status of private object.'), ('can_change_privacy', 'Can change object privacy.'), ('can_revert', 'Can revert live object from historical object.'), ('can_branch', 'Can branch the object to a new wiqi.'), ('can_merge', 'Can merge the object into an existing wiqi.'), ('purchased', 'Has purchased the object.'), ('borrowed', 'Has borrowed the object.'), ('can_share_view', 'Can share access of private object with others.'), ('can_share_view_stack', 'Can share access of view history.'), ('can_share_edit', 'Can share access of edit private object.'), ('can_share_publish', 'Can share access of change publication status.'), ('can_share_privacy', 'Can share access of change object privacy.'), ('can_share_revert', 'Can share access of revert live object.'), ('can_share_branch', 'Can share access of branch to a new wiqi.'), ('can_share_merge', 'Can share access of merge into an existing wiqi.')),
            },
            managers=[
                ('wiqi_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='wiqi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiqi.Wiqi'),
        ),
    ]
