# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 17:56
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('wiqi', '0002_auto_20150210_0848'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='text',
            managers=[
                ('wiqi_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='wiqi',
            managers=[
                ('wiqi_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
