# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiqi', '0003_auto_20160322_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='custom_div',
            field=models.TextField(blank=True, help_text=b'Use html format to enter text.', verbose_name=b'Custom Div'),
        ),
        migrations.AlterField(
            model_name='wiqi',
            name='read_if',
            field=models.CharField(choices=[(b'open', b'Open'), (b'login', b'Login'), (b'own', b'Own')], default=b'own', max_length=5),
        ),
    ]
